# Generated by Django 4.2.3 on 2023-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
