# Generated by Django 4.2.3 on 2023-07-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='date',
            new_name='created_at',
        ),
    ]
